variable "description_default" {}
variable "env" {}
variable "iam_role" {}
variable "project_name" {}
variable "tag_business_region" {}
variable "tag_business_unit" {}
variable "tag_client" {}
variable "tag_platform" {}
variable "tag_resource_created_by" {}
variable "aws_region" {}
variable "chat_engine_token_lambda_invoke_arn" {}
variable "ui_api_lambda_invoke_arn" {}
variable "chat_engine_backend_lambda_invoke_arn" {}
variable "api_integrator_lambda_invoke_arn" {}
variable "s3_file_operations_lambda_invoke_arn" {}
variable "twilio_integrator_lambda_invoke_arn" {}
variable "starhub_integrator_lambda_invoke_arn" {}
variable "optus_lambda_invoke_arn" {}