variable "asurion_net_dns" {}
variable "asurion53_dns" {}
variable "aws_region" {}
variable "project_name" {}
variable "tag_business_region" {}
variable "tag_business_unit" {}
variable "tag_client" {}
variable "tag_platform" {}
variable "tag_resource_created_by" {}
variable "tag_email_distribution" {}
variable "env" {}
variable "zone" {}
variable "tag_environment" {}