variable "aws_region" {}
variable "iam_role" {}
variable "env" {}
variable "project_name" {}
variable "tag_business_region" {}
variable "tag_business_unit" {}
variable "tag_client" {}
variable "tag_environment" {}
variable "tag_platform" {}
variable "tag_resource_created_by" {}
variable "env_version" {}